### ISSUE TITLE
Facebook Firebase mediation

### ISSUE THREAD

**Issue by solankiranvir** [pallopmax/AdMobMediationAdapterFB#2]
Hello I have to implement Facebook Mediation for Firebase ads.I downloaded your FacebookMediationAdapter but don't know how to use this in my android app so have you any project in which you use it & load banner & Interstitial ads?

**Comment by pallopmax** [comment]
set eCPM, mediation load auto from AdMob code.  You can read from https://support.google.com/admob/answer/3063564

req admob & fb sdk & mediation.

`  compile 'com.google.firebase:firebase-ads:9.4.0'
    compile 'com.facebook.android:audience-network-sdk:4.15.0'
    compile 'com.github.pallopmax:admobmediationadapterfb:1.2.0'`

**Comment by solankiranvir** [comment]
Okay @pallopmax But where or how to initial lize FBAdapter in my Code because there is no documentation for define meta data & code for using FBAdapter.
I already use admob ads code for load ads & intialize ADMObMobile SDK but what next?

**Comment by pallopmax** [comment]
Do not do anything with adapter, try set eCPM Facebook highter than AdMob and run you app. Adapter show when FB eCPM > AdMob eCPM.

**Comment by solankiranvir** [comment]
Okay i will check. But i define meta data for facebook interstial in menifest right?

**Comment by pallopmax** [comment]
Yes, adapter load from FB audience network SDK.

**Comment by solankiranvir** [comment]
Okay any otgher thing define in menifest for fb adapter? or just include adapter in gradle?

**Comment by pallopmax** [comment]
`compile 'com.github.pallopmax:admobmediationadapterfb:1.2.0'` or add .jar in project

```
<activity android:name="com.facebook.ads.InterstitialAdActivity"
            android:configChanges="keyboardHidden|orientation|screenSize" />
```

**Comment by solankiranvir** [comment]
Okay i understand now thanks :-)

**Comment by pallopmax** [comment]
Sorry, My english is bad. Good Luck @solankiranvir

**Comment by solankiranvir** [comment]
Hmm No issue buddy :-)

**Comment by solankiranvir** [comment]
Hmm No issue buddy :-)
